name: DamageIndicator
main: com.zenya.damageindicator.DamageIndicator
version: 0.0.3
author: Zenya4
description: A high performance packet-based damage indicator
api-version: 1.13

commands:
  damageindicator:
    description: Main command for DamageIndicator
    aliases:
      - di
    permission: damageindicator.command.help
    usage: /<command>