name: DamageIndicator
main: com.zenya.damageindicator.DamageIndicator
version: ${version}
authors: [ Insprill, Zenya4 ]
description: A high performance packet-based damage indicator
api-version: 1.13

permissions:
  damageindicator.command.toggle:
    default: true
