name: DamageIndicator
main: com.zenya.damageindicator.DamageIndicator
version: 1.1.5
authors: [Insprill, Zenya4]
description: A high performance packet-based damage indicator
api-version: 1.13

commands:
  damageindicator:
    description: Main command for DamageIndicator
    aliases:
      - di
    permission: damageindicator.command.help
    usage: /<command>

permissions:
  damageindicator.*:
    children:
      damageindicator.command.help: true
      damageindicator.command.toggle: true
      damageindicator.command.reload: true
  damageindicator.command.*:
    children:
      damageindicator.command.help: true
      damageindicator.command.toggle: true
      damageindicator.command.reload: true
  damageindicator.command.help:
    default: true
  damageindicator.command.toggle:
    default: true
  damageindicator.command.reload:
    default: op
