name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        java8_bt_version: [ 1.8.3, 1.8.8, 1.9.2, 1.9.4, 1.10.2, 1.11.2, 1.12.2, 1.13, 1.13.2, 1.14.4, 1.15.2, 1.16.1, 1.16.3, 1.16.5 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Download BuildTools
        run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Run BuildTools ${{ matrix.java8_bt_version }}
        run: java -jar BuildTools.jar --rev ${{ matrix.java8_bt_version }}

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: 'temurin'

      - name: Run BuildTools 1.17
        run: java -jar BuildTools.jar --rev 1.17
        # paperweight is used for 1.17.1+

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@master

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Compiled JARs
          path: build/libs
